version: 2.1
orbs:
  macos: circleci/macos@2.4.1
jobs:
  build-test:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - run: echo 'hello'
      - macos/add-uitest-permissions
      - run: echo test'
      - run: echo 'test'
      
enable-vnc:
workflows:
  verify:
    jobs:
      - build-test