version: 2.1
orbs:
  macos: circleci/macos@2.4.1
jobs:
  build-test:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - macos/add-uitest-permissions
      
enable-vnc:
workflows:
  verify:
    jobs:
      - build-test