name: Setup SSH Server with ngrok

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ngrok
        run: |
          brew install --cask ngrok

      - name: Set up ngrok Auth token
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Install SSH server
        run: |
          brew install openssh
          sudo systemsetup -setremotelogin on
          sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

      - name: Start ngrok and forward SSH port
        run: |
          ngrok tcp 22
